boundary:
  controller:
    addr: 10.5.0.5
    port: 9200

squid:
  port: 3128

  # An empty value [] means accepting all traffic, increasing costs.
  allowed_domains:
    - example.com
    - test.com
